version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: ./dockerfile
    ports:
      - "8080:8081"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_DB=hezzl

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379

      - NATS_URL=${NATS_URL}
    restart: on-failure
    links:
      - "postgres:postgres"

  postgres:
    image: postgres:latest
    volumes:
      - my-db:/var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=hezzl
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222"   # NATS server
      - "8222:8222"   # NATS HTTP monitoring

  # не успел добраться до clickhouse
  # clickhouse:
  #   image: yandex/clickhouse-server
  #   ports:
  #     - "8123:8123"   # HTTP interface
  #     - "9000:9000"   # Native interface
  #     - "9009:9009"   # MySQL protocol
  #   volumes:
  #     - /path/to/clickhouse/data:/var/lib/clickhouse   # Data directory
  #     - /path/to/clickhouse/config:/etc/clickhouse-server   # Configuration directory
  #   environment:
  #     - CLICKHOUSE_CONFIG_DIR=/etc/clickhouse-server
  #     - CLICKHOUSE_LOG_DIR=/var/log/clickhouse-server
  #     - CLICKHOUSE_USER=default
  #     - CLICKHOUSE_PASSWORD=password

volumes:
  my-db:
  redis_data: